# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QStatusBar, QTextBrowser, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1930, 1068)
        self.actiondark = QAction(MainWindow)
        self.actiondark.setObjectName(u"actiondark")
        self.actionlight = QAction(MainWindow)
        self.actionlight.setObjectName(u"actionlight")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(30, 30, 611, 481))
        font = QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.microphoneMBox = QComboBox(self.groupBox)
        self.microphoneMBox.setObjectName(u"microphoneMBox")
        self.microphoneMBox.setGeometry(QRect(120, 100, 241, 31))
        self.microphoneMBox.setFont(font)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 100, 111, 31))
        self.label.setFont(font)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 50, 81, 16))
        self.label_6.setFont(font)
        self.recognizerMBOX = QComboBox(self.groupBox)
        self.recognizerMBOX.setObjectName(u"recognizerMBOX")
        self.recognizerMBOX.setGeometry(QRect(120, 50, 241, 31))
        self.recognizerMBOX.setFont(font)
        self.whisperGroupBox = QGroupBox(self.groupBox)
        self.whisperGroupBox.setObjectName(u"whisperGroupBox")
        self.whisperGroupBox.setGeometry(QRect(10, 160, 511, 251))
        self.whisperGroupBox.setFont(font)
        self.whisperModel = QComboBox(self.whisperGroupBox)
        self.whisperModel.setObjectName(u"whisperModel")
        self.whisperModel.setGeometry(QRect(100, 40, 241, 34))
        self.whisperModel.setFont(font)
        self.label_12 = QLabel(self.whisperGroupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 40, 61, 16))
        self.label_12.setFont(font)
        self.label_13 = QLabel(self.whisperGroupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 90, 81, 31))
        self.label_13.setFont(font)
        self.whisperDevice = QComboBox(self.whisperGroupBox)
        self.whisperDevice.setObjectName(u"whisperDevice")
        self.whisperDevice.setGeometry(QRect(101, 91, 241, 34))
        self.whisperDevice.setFont(font)
        self.whisperLanguage = QComboBox(self.whisperGroupBox)
        self.whisperLanguage.setObjectName(u"whisperLanguage")
        self.whisperLanguage.setGeometry(QRect(100, 140, 241, 34))
        self.whisperLanguage.setFont(font)
        self.label_14 = QLabel(self.whisperGroupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 130, 91, 41))
        self.label_14.setFont(font)
        self.googleGroupBox = QGroupBox(self.groupBox)
        self.googleGroupBox.setObjectName(u"googleGroupBox")
        self.googleGroupBox.setGeometry(QRect(10, 160, 511, 231))
        self.googleGroupBox.setFont(font)
        self.label_2 = QLabel(self.googleGroupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 101, 31))
        self.label_2.setFont(font)
        self.googleLanguage = QComboBox(self.googleGroupBox)
        self.googleLanguage.setObjectName(u"googleLanguage")
        self.googleLanguage.setGeometry(QRect(120, 50, 131, 31))
        self.googleLanguage.setFont(font)
        self.label_3 = QLabel(self.googleGroupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 100, 81, 31))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.googleGroupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 160, 91, 31))
        self.label_4.setFont(font)
        self.googleAPI = QLineEdit(self.googleGroupBox)
        self.googleAPI.setObjectName(u"googleAPI")
        self.googleAPI.setGeometry(QRect(120, 110, 381, 31))
        self.googleAPI.setFont(font)
        self.googleEndPoint = QLineEdit(self.googleGroupBox)
        self.googleEndPoint.setObjectName(u"googleEndPoint")
        self.googleEndPoint.setGeometry(QRect(120, 170, 381, 31))
        self.googleEndPoint.setFont(font)
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(660, 20, 641, 511))
        self.groupBox_6.setFont(font)
        self.groupBox_7 = QGroupBox(self.groupBox_6)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 100, 601, 401))
        self.groupBox_7.setFont(font)
        self.testConnectionOpenAI = QPushButton(self.groupBox_7)
        self.testConnectionOpenAI.setObjectName(u"testConnectionOpenAI")
        self.testConnectionOpenAI.setGeometry(QRect(370, 340, 81, 31))
        self.testConnectionOpenAI.setFont(font)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.Phone))
        self.testConnectionOpenAI.setIcon(icon)
        self.testConnectionOpenAI.setIconSize(QSize(16, 16))
#if QT_CONFIG(shortcut)
        self.testConnectionOpenAI.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.resetDefaultsOpenAI = QPushButton(self.groupBox_7)
        self.resetDefaultsOpenAI.setObjectName(u"resetDefaultsOpenAI")
        self.resetDefaultsOpenAI.setGeometry(QRect(460, 340, 81, 31))
        self.resetDefaultsOpenAI.setFont(font)
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentRevert))
        self.resetDefaultsOpenAI.setIcon(icon1)
        self.label_18 = QLabel(self.groupBox_7)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 250, 141, 31))
        self.label_18.setFont(font)
        self.systemPromptEdit = QTextEdit(self.groupBox_7)
        self.systemPromptEdit.setObjectName(u"systemPromptEdit")
        self.systemPromptEdit.setGeometry(QRect(160, 240, 381, 91))
        self.systemPromptEdit.setFont(font)
        self.maxTokenOpenAI = QSpinBox(self.groupBox_7)
        self.maxTokenOpenAI.setObjectName(u"maxTokenOpenAI")
        self.maxTokenOpenAI.setGeometry(QRect(170, 180, 101, 31))
        self.maxTokenOpenAI.setFont(font)
        self.maxTokenOpenAI.setMinimum(1)
        self.maxTokenOpenAI.setMaximum(4096)
        self.maxTokenOpenAI.setValue(1024)
        self.openaiAPIKey = QLineEdit(self.groupBox_7)
        self.openaiAPIKey.setObjectName(u"openaiAPIKey")
        self.openaiAPIKey.setGeometry(QRect(170, 40, 411, 34))
        self.openaiAPIKey.setFont(font)
        self.label_19 = QLabel(self.groupBox_7)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 40, 81, 26))
        self.label_19.setFont(font)
        self.llmMBOX = QComboBox(self.groupBox_7)
        self.llmMBOX.setObjectName(u"llmMBOX")
        self.llmMBOX.setGeometry(QRect(170, 80, 181, 34))
        self.llmMBOX.setFont(font)
        self.label_21 = QLabel(self.groupBox_7)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 170, 99, 40))
        self.label_21.setFont(font)
        self.label_22 = QLabel(self.groupBox_7)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 130, 106, 26))
        self.label_22.setFont(font)
        self.label_23 = QLabel(self.groupBox_7)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(31, 82, 54, 26))
        self.label_23.setFont(font)
        self.temperatureOpenAI = QSlider(self.groupBox_7)
        self.temperatureOpenAI.setObjectName(u"temperatureOpenAI")
        self.temperatureOpenAI.setGeometry(QRect(200, 130, 181, 16))
        self.temperatureOpenAI.setFont(font)
        self.temperatureOpenAI.setMaximum(100)
        self.temperatureOpenAI.setSingleStep(1)
        self.temperatureOpenAI.setValue(70)
        self.temperatureOpenAI.setOrientation(Qt.Orientation.Horizontal)
        self.LLMChocie = QComboBox(self.groupBox_6)
        self.LLMChocie.setObjectName(u"LLMChocie")
        self.LLMChocie.setGeometry(QRect(110, 50, 211, 24))
        self.LLMChocie.setFont(font)
        self.label_24 = QLabel(self.groupBox_6)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 50, 51, 21))
        self.label_24.setFont(font)
        self.themeComboBox = QComboBox(self.centralwidget)
        self.themeComboBox.setObjectName(u"themeComboBox")
        self.themeComboBox.setGeometry(QRect(1690, 0, 131, 31))
        self.themeComboBox.setFont(font)
        self.label_25 = QLabel(self.centralwidget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(1530, 0, 111, 20))
        self.label_25.setFont(font)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(660, 790, 391, 111))
        self.groupBox_2.setFont(font)
        self.startASR = QPushButton(self.groupBox_2)
        self.startASR.setObjectName(u"startASR")
        self.startASR.setGeometry(QRect(10, 50, 101, 41))
        self.startASR.setFont(font)
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackStart))
        self.startASR.setIcon(icon2)
        self.clearASR = QPushButton(self.groupBox_2)
        self.clearASR.setObjectName(u"clearASR")
        self.clearASR.setGeometry(QRect(130, 50, 101, 41))
        self.clearASR.setFont(font)
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ViewRestore))
        self.clearASR.setIcon(icon3)
        self.stopASR = QPushButton(self.groupBox_2)
        self.stopASR.setObjectName(u"stopASR")
        self.stopASR.setGeometry(QRect(260, 50, 111, 41))
        self.stopASR.setFont(font)
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackStop))
        self.stopASR.setIcon(icon4)
        self.contextBrowserOpenAI = QTextBrowser(self.centralwidget)
        self.contextBrowserOpenAI.setObjectName(u"contextBrowserOpenAI")
        self.contextBrowserOpenAI.setGeometry(QRect(520, 540, 701, 231))
        self.contextBrowserOpenAI.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1930, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuGUI_Theme = QMenu(self.menuView)
        self.menuGUI_Theme.setObjectName(u"menuGUI_Theme")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuView.addAction(self.menuGUI_Theme.menuAction())
        self.menuGUI_Theme.addAction(self.actiondark)
        self.menuGUI_Theme.addAction(self.actionlight)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actiondark.setText(QCoreApplication.translate("MainWindow", u"dark", None))
        self.actionlight.setText(QCoreApplication.translate("MainWindow", u"light", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Automatic Speech Recognition", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Microphone", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"ASR", None))
        self.whisperGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Whisper Options", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Device", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Language", None))
        self.googleGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Google Options", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Language", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"API Key", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Endpoint", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Large Language Model", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"OpenAI Options", None))
        self.testConnectionOpenAI.setText("")
        self.resetDefaultsOpenAI.setText("")
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"System Prompt", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"API Key", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Max-tokens", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Temperature", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"LLM", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"GUI theme", None))
        self.groupBox_2.setTitle("")
        self.startASR.setText("")
        self.clearASR.setText("")
        self.stopASR.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuGUI_Theme.setTitle(QCoreApplication.translate("MainWindow", u"GUI Theme", None))
    # retranslateUi

