# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSlider, QSpinBox, QSplitter,
    QStatusBar, QTextBrowser, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1984, 1036)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(110, 120, 441, 531))
        self.microphoneMBox = QComboBox(self.groupBox)
        self.microphoneMBox.setObjectName(u"microphoneMBox")
        self.microphoneMBox.setGeometry(QRect(120, 70, 241, 24))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 70, 81, 16))
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 290, 351, 61))
        self.startASR = QPushButton(self.groupBox_2)
        self.startASR.setObjectName(u"startASR")
        self.startASR.setGeometry(QRect(10, 30, 101, 24))
        self.clearASR = QPushButton(self.groupBox_2)
        self.clearASR.setObjectName(u"clearASR")
        self.clearASR.setGeometry(QRect(120, 30, 101, 24))
        self.stopASR = QPushButton(self.groupBox_2)
        self.stopASR.setObjectName(u"stopASR")
        self.stopASR.setGeometry(QRect(230, 30, 101, 24))
        self.asrTextBrowser = QTextBrowser(self.groupBox)
        self.asrTextBrowser.setObjectName(u"asrTextBrowser")
        self.asrTextBrowser.setGeometry(QRect(10, 370, 351, 131))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 40, 81, 16))
        self.recognizerMBOX = QComboBox(self.groupBox)
        self.recognizerMBOX.setObjectName(u"recognizerMBOX")
        self.recognizerMBOX.setGeometry(QRect(120, 40, 241, 24))
        self.googleGroupBox = QGroupBox(self.groupBox)
        self.googleGroupBox.setObjectName(u"googleGroupBox")
        self.googleGroupBox.setGeometry(QRect(10, 100, 421, 171))
        self.label_2 = QLabel(self.googleGroupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 61, 16))
        self.googleLanguage = QComboBox(self.googleGroupBox)
        self.googleLanguage.setObjectName(u"googleLanguage")
        self.googleLanguage.setGeometry(QRect(120, 40, 91, 24))
        self.label_3 = QLabel(self.googleGroupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 70, 81, 16))
        self.label_4 = QLabel(self.googleGroupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 100, 91, 16))
        self.googleAPI = QLineEdit(self.googleGroupBox)
        self.googleAPI.setObjectName(u"googleAPI")
        self.googleAPI.setGeometry(QRect(120, 70, 291, 24))
        self.googleEndPoint = QLineEdit(self.googleGroupBox)
        self.googleEndPoint.setObjectName(u"googleEndPoint")
        self.googleEndPoint.setGeometry(QRect(120, 100, 291, 24))
        self.whisperGroupBox = QGroupBox(self.groupBox)
        self.whisperGroupBox.setObjectName(u"whisperGroupBox")
        self.whisperGroupBox.setGeometry(QRect(10, 100, 211, 181))
        self.whisperModel = QComboBox(self.whisperGroupBox)
        self.whisperModel.setObjectName(u"whisperModel")
        self.whisperModel.setGeometry(QRect(80, 40, 72, 24))
        self.label_12 = QLabel(self.whisperGroupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 40, 61, 16))
        self.label_13 = QLabel(self.whisperGroupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 70, 61, 16))
        self.whisperDevice = QComboBox(self.whisperGroupBox)
        self.whisperDevice.setObjectName(u"whisperDevice")
        self.whisperDevice.setGeometry(QRect(80, 70, 72, 24))
        self.whisperLanguage = QComboBox(self.whisperGroupBox)
        self.whisperLanguage.setObjectName(u"whisperLanguage")
        self.whisperLanguage.setGeometry(QRect(80, 100, 72, 24))
        self.label_14 = QLabel(self.whisperGroupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 100, 61, 16))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(680, 120, 491, 641))
        self.groupBox_4 = QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 110, 431, 251))
        self.textEdit = QTextEdit(self.groupBox_4)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(120, 110, 301, 70))
        self.label_10 = QLabel(self.groupBox_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 110, 84, 25))
        self.splitter = QSplitter(self.groupBox_4)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(30, 30, 341, 24))
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.label_5 = QLabel(self.splitter)
        self.label_5.setObjectName(u"label_5")
        self.splitter.addWidget(self.label_5)
        self.lineEdit = QLineEdit(self.splitter)
        self.lineEdit.setObjectName(u"lineEdit")
        self.splitter.addWidget(self.lineEdit)
        self.splitter_2 = QSplitter(self.groupBox_4)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(30, 60, 151, 16))
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.label_8 = QLabel(self.splitter_2)
        self.label_8.setObjectName(u"label_8")
        self.splitter_2.addWidget(self.label_8)
        self.horizontalSlider = QSlider(self.splitter_2)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setValue(70)
        self.horizontalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_2.addWidget(self.horizontalSlider)
        self.splitter_3 = QSplitter(self.groupBox_4)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(30, 80, 171, 25))
        self.splitter_3.setOrientation(Qt.Orientation.Horizontal)
        self.label_9 = QLabel(self.splitter_3)
        self.label_9.setObjectName(u"label_9")
        self.splitter_3.addWidget(self.label_9)
        self.spinBox = QSpinBox(self.splitter_3)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(4096)
        self.spinBox.setValue(1024)
        self.splitter_3.addWidget(self.spinBox)
        self.groupBox_5 = QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 380, 431, 251))
        self.textEdit_2 = QTextEdit(self.groupBox_5)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(120, 110, 301, 70))
        self.label_11 = QLabel(self.groupBox_5)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 110, 84, 25))
        self.splitter_5 = QSplitter(self.groupBox_5)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setGeometry(QRect(30, 30, 341, 24))
        self.splitter_5.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_6 = QSplitter(self.groupBox_5)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setGeometry(QRect(30, 60, 151, 16))
        self.splitter_6.setOrientation(Qt.Orientation.Horizontal)
        self.label_16 = QLabel(self.splitter_6)
        self.label_16.setObjectName(u"label_16")
        self.splitter_6.addWidget(self.label_16)
        self.horizontalSlider_2 = QSlider(self.splitter_6)
        self.horizontalSlider_2.setObjectName(u"horizontalSlider_2")
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setSingleStep(1)
        self.horizontalSlider_2.setValue(70)
        self.horizontalSlider_2.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_6.addWidget(self.horizontalSlider_2)
        self.splitter_7 = QSplitter(self.groupBox_5)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setGeometry(QRect(30, 80, 171, 25))
        self.splitter_7.setOrientation(Qt.Orientation.Horizontal)
        self.label_17 = QLabel(self.splitter_7)
        self.label_17.setObjectName(u"label_17")
        self.splitter_7.addWidget(self.label_17)
        self.spinBox_2 = QSpinBox(self.splitter_7)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(4096)
        self.spinBox_2.setValue(1024)
        self.splitter_7.addWidget(self.spinBox_2)
        self.splitter_4 = QSplitter(self.groupBox_3)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setGeometry(QRect(60, 70, 221, 24))
        self.splitter_4.setOrientation(Qt.Orientation.Horizontal)
        self.label_7 = QLabel(self.splitter_4)
        self.label_7.setObjectName(u"label_7")
        self.splitter_4.addWidget(self.label_7)
        self.llmMBOX = QComboBox(self.splitter_4)
        self.llmMBOX.setObjectName(u"llmMBOX")
        self.splitter_4.addWidget(self.llmMBOX)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1984, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Automatic Speech Recognition", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Microphone", None))
        self.groupBox_2.setTitle("")
        self.startASR.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.clearASR.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.stopASR.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"ASR", None))
        self.googleGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Google Options", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Language", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"API", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Endpoint", None))
        self.whisperGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Whisper Options", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Device", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Language", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Large Language Model", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"OpenAI Options", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Context", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"API Key", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Temperature", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Max-tokens", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"LLAMA Options", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Context", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Temperature", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Max-tokens", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"LLM", None))
    # retranslateUi

