# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSlider, QSpinBox, QSplitter,
    QStatusBar, QTextBrowser, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1984, 1036)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(680, 120, 491, 641))
        self.splitter_4 = QSplitter(self.groupBox_3)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setGeometry(QRect(20, 30, 221, 24))
        self.splitter_4.setOrientation(Qt.Orientation.Horizontal)
        self.label_7 = QLabel(self.splitter_4)
        self.label_7.setObjectName(u"label_7")
        self.splitter_4.addWidget(self.label_7)
        self.llmMBOX = QComboBox(self.splitter_4)
        self.llmMBOX.setObjectName(u"llmMBOX")
        self.splitter_4.addWidget(self.llmMBOX)
        self.groupBox_4 = QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 90, 471, 521))
        self.splitter = QSplitter(self.groupBox_4)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(30, 30, 341, 24))
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.label_5 = QLabel(self.splitter)
        self.label_5.setObjectName(u"label_5")
        self.splitter.addWidget(self.label_5)
        self.lineEdit = QLineEdit(self.splitter)
        self.lineEdit.setObjectName(u"lineEdit")
        self.splitter.addWidget(self.lineEdit)
        self.splitter_2 = QSplitter(self.groupBox_4)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(30, 60, 151, 16))
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.label_8 = QLabel(self.splitter_2)
        self.label_8.setObjectName(u"label_8")
        self.splitter_2.addWidget(self.label_8)
        self.horizontalSlider = QSlider(self.splitter_2)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setValue(70)
        self.horizontalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_2.addWidget(self.horizontalSlider)
        self.splitter_3 = QSplitter(self.groupBox_4)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(30, 80, 171, 25))
        self.splitter_3.setOrientation(Qt.Orientation.Horizontal)
        self.label_9 = QLabel(self.splitter_3)
        self.label_9.setObjectName(u"label_9")
        self.splitter_3.addWidget(self.label_9)
        self.spinBox = QSpinBox(self.splitter_3)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(4096)
        self.spinBox.setValue(1024)
        self.splitter_3.addWidget(self.spinBox)
        self.resetContextButton = QPushButton(self.groupBox_4)
        self.resetContextButton.setObjectName(u"resetContextButton")
        self.resetContextButton.setGeometry(QRect(280, 480, 171, 25))
        self.testConnectionOpenAI = QPushButton(self.groupBox_4)
        self.testConnectionOpenAI.setObjectName(u"testConnectionOpenAI")
        self.testConnectionOpenAI.setGeometry(QRect(10, 300, 171, 25))
        self.resetDefaultsOpenAI = QPushButton(self.groupBox_4)
        self.resetDefaultsOpenAI.setObjectName(u"resetDefaultsOpenAI")
        self.resetDefaultsOpenAI.setGeometry(QRect(260, 300, 171, 25))
        self.splitter_8 = QSplitter(self.groupBox_4)
        self.splitter_8.setObjectName(u"splitter_8")
        self.splitter_8.setGeometry(QRect(20, 110, 401, 81))
        self.splitter_8.setOrientation(Qt.Orientation.Horizontal)
        self.label_18 = QLabel(self.splitter_8)
        self.label_18.setObjectName(u"label_18")
        self.splitter_8.addWidget(self.label_18)
        self.systemPromptEdit = QTextEdit(self.splitter_8)
        self.systemPromptEdit.setObjectName(u"systemPromptEdit")
        self.splitter_8.addWidget(self.systemPromptEdit)
        self.splitter_9 = QSplitter(self.groupBox_4)
        self.splitter_9.setObjectName(u"splitter_9")
        self.splitter_9.setGeometry(QRect(20, 200, 401, 81))
        self.splitter_9.setOrientation(Qt.Orientation.Horizontal)
        self.label_20 = QLabel(self.splitter_9)
        self.label_20.setObjectName(u"label_20")
        self.splitter_9.addWidget(self.label_20)
        self.systemPromptEdit_2 = QTextEdit(self.splitter_9)
        self.systemPromptEdit_2.setObjectName(u"systemPromptEdit_2")
        self.splitter_9.addWidget(self.systemPromptEdit_2)
        self.splitter_10 = QSplitter(self.groupBox_4)
        self.splitter_10.setObjectName(u"splitter_10")
        self.splitter_10.setGeometry(QRect(20, 330, 401, 111))
        self.splitter_10.setOrientation(Qt.Orientation.Horizontal)
        self.label_context = QLabel(self.splitter_10)
        self.label_context.setObjectName(u"label_context")
        self.splitter_10.addWidget(self.label_context)
        self.contextTextBrowser = QTextBrowser(self.splitter_10)
        self.contextTextBrowser.setObjectName(u"contextTextBrowser")
        self.splitter_10.addWidget(self.contextTextBrowser)
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(1230, 250, 431, 311))
        self.splitter_5 = QSplitter(self.groupBox_5)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setGeometry(QRect(30, 30, 341, 24))
        self.splitter_5.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_6 = QSplitter(self.groupBox_5)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setGeometry(QRect(30, 60, 151, 16))
        self.splitter_6.setOrientation(Qt.Orientation.Horizontal)
        self.label_16 = QLabel(self.splitter_6)
        self.label_16.setObjectName(u"label_16")
        self.splitter_6.addWidget(self.label_16)
        self.horizontalSlider_2 = QSlider(self.splitter_6)
        self.horizontalSlider_2.setObjectName(u"horizontalSlider_2")
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setSingleStep(1)
        self.horizontalSlider_2.setValue(70)
        self.horizontalSlider_2.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_6.addWidget(self.horizontalSlider_2)
        self.splitter_7 = QSplitter(self.groupBox_5)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setGeometry(QRect(30, 80, 171, 25))
        self.splitter_7.setOrientation(Qt.Orientation.Horizontal)
        self.label_17 = QLabel(self.splitter_7)
        self.label_17.setObjectName(u"label_17")
        self.splitter_7.addWidget(self.label_17)
        self.spinBox_2 = QSpinBox(self.splitter_7)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(4096)
        self.spinBox_2.setValue(1024)
        self.splitter_7.addWidget(self.spinBox_2)
        self.label_19 = QLabel(self.groupBox_5)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 110, 100, 25))
        self.systemPromptEditLlama = QTextEdit(self.groupBox_5)
        self.systemPromptEditLlama.setObjectName(u"systemPromptEditLlama")
        self.systemPromptEditLlama.setGeometry(QRect(120, 110, 301, 70))
        self.testConnectionLlama = QPushButton(self.groupBox_5)
        self.testConnectionLlama.setObjectName(u"testConnectionLlama")
        self.testConnectionLlama.setGeometry(QRect(30, 190, 171, 25))
        self.resetDefaultsLlama = QPushButton(self.groupBox_5)
        self.resetDefaultsLlama.setObjectName(u"resetDefaultsLlama")
        self.resetDefaultsLlama.setGeometry(QRect(220, 190, 171, 25))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1984, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Large Language Model", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"LLM", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"OpenAI Options", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"API Key", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Temperature", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Max-tokens", None))
        self.resetContextButton.setText(QCoreApplication.translate("MainWindow", u"Reset Context", None))
        self.testConnectionOpenAI.setText(QCoreApplication.translate("MainWindow", u"Test Connection", None))
        self.resetDefaultsOpenAI.setText(QCoreApplication.translate("MainWindow", u"Reset Defaults", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"System Prompt", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"User Input", None))
        self.label_context.setText(QCoreApplication.translate("MainWindow", u"Context", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"LLAMA Options", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Temperature", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Max-tokens", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"System Prompt", None))
        self.testConnectionLlama.setText(QCoreApplication.translate("MainWindow", u"Test Connection", None))
        self.resetDefaultsLlama.setText(QCoreApplication.translate("MainWindow", u"Reset Defaults", None))
    # retranslateUi

