# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QStatusBar, QTextBrowser, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(831, 1036)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(160, 40, 621, 871))
        font = QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_4 = QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 100, 601, 761))
        self.groupBox_4.setFont(font)
        self.testConnectionOpenAI = QPushButton(self.groupBox_4)
        self.testConnectionOpenAI.setObjectName(u"testConnectionOpenAI")
        self.testConnectionOpenAI.setGeometry(QRect(370, 340, 81, 31))
        self.testConnectionOpenAI.setFont(font)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.Phone))
        self.testConnectionOpenAI.setIcon(icon)
        self.testConnectionOpenAI.setIconSize(QSize(16, 16))
#if QT_CONFIG(shortcut)
        self.testConnectionOpenAI.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.resetDefaultsOpenAI = QPushButton(self.groupBox_4)
        self.resetDefaultsOpenAI.setObjectName(u"resetDefaultsOpenAI")
        self.resetDefaultsOpenAI.setGeometry(QRect(450, 340, 81, 31))
        self.resetDefaultsOpenAI.setFont(font)
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentRevert))
        self.resetDefaultsOpenAI.setIcon(icon1)
        self.groupBoxChat = QGroupBox(self.groupBox_4)
        self.groupBoxChat.setObjectName(u"groupBoxChat")
        self.groupBoxChat.setGeometry(QRect(10, 360, 571, 391))
        self.groupBoxChat.setFont(font)
        self.sendUserInputOpenAI = QPushButton(self.groupBoxChat)
        self.sendUserInputOpenAI.setObjectName(u"sendUserInputOpenAI")
        self.sendUserInputOpenAI.setGeometry(QRect(360, 170, 71, 31))
        self.sendUserInputOpenAI.setFont(font)
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSend))
        self.sendUserInputOpenAI.setIcon(icon2)
        self.sendUserInputOpenAI.setCheckable(True)
        self.resetContextOpenAI = QPushButton(self.groupBoxChat)
        self.resetContextOpenAI.setObjectName(u"resetContextOpenAI")
        self.resetContextOpenAI.setGeometry(QRect(360, 350, 71, 31))
        self.resetContextOpenAI.setFont(font)
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditUndo))
        self.resetContextOpenAI.setIcon(icon3)
        self.contextBrowserOpenAI = QTextBrowser(self.groupBoxChat)
        self.contextBrowserOpenAI.setObjectName(u"contextBrowserOpenAI")
        self.contextBrowserOpenAI.setGeometry(QRect(140, 210, 381, 131))
        self.contextBrowserOpenAI.setFont(font)
        self.label_context = QLabel(self.groupBoxChat)
        self.label_context.setObjectName(u"label_context")
        self.label_context.setGeometry(QRect(10, 230, 81, 41))
        self.label_context.setFont(font)
        self.label_20 = QLabel(self.groupBoxChat)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 60, 111, 41))
        self.label_20.setFont(font)
        self.userInputOpenAI = QTextEdit(self.groupBoxChat)
        self.userInputOpenAI.setObjectName(u"userInputOpenAI")
        self.userInputOpenAI.setGeometry(QRect(140, 30, 381, 132))
        self.userInputOpenAI.setFont(font)
        self.label_18 = QLabel(self.groupBox_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 250, 141, 31))
        self.label_18.setFont(font)
        self.systemPromptEdit = QTextEdit(self.groupBox_4)
        self.systemPromptEdit.setObjectName(u"systemPromptEdit")
        self.systemPromptEdit.setGeometry(QRect(160, 240, 381, 91))
        self.systemPromptEdit.setFont(font)
        self.chatModeOpenAI = QCheckBox(self.groupBox_4)
        self.chatModeOpenAI.setObjectName(u"chatModeOpenAI")
        self.chatModeOpenAI.setGeometry(QRect(230, 350, 21, 21))
        self.chatModeOpenAI.setFont(font)
        self.label = QLabel(self.groupBox_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 350, 181, 16))
        self.label.setFont(font)
        self.maxTokenOpenAI = QSpinBox(self.groupBox_4)
        self.maxTokenOpenAI.setObjectName(u"maxTokenOpenAI")
        self.maxTokenOpenAI.setGeometry(QRect(170, 180, 101, 31))
        self.maxTokenOpenAI.setFont(font)
        self.maxTokenOpenAI.setMinimum(1)
        self.maxTokenOpenAI.setMaximum(4096)
        self.maxTokenOpenAI.setValue(1024)
        self.openaiAPIKey = QLineEdit(self.groupBox_4)
        self.openaiAPIKey.setObjectName(u"openaiAPIKey")
        self.openaiAPIKey.setGeometry(QRect(170, 40, 411, 34))
        self.openaiAPIKey.setFont(font)
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 40, 81, 26))
        self.label_5.setFont(font)
        self.llmMBOX = QComboBox(self.groupBox_4)
        self.llmMBOX.setObjectName(u"llmMBOX")
        self.llmMBOX.setGeometry(QRect(170, 80, 181, 34))
        self.llmMBOX.setFont(font)
        self.label_9 = QLabel(self.groupBox_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 170, 99, 40))
        self.label_9.setFont(font)
        self.label_8 = QLabel(self.groupBox_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 130, 106, 26))
        self.label_8.setFont(font)
        self.label_6 = QLabel(self.groupBox_4)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(31, 82, 54, 26))
        self.label_6.setFont(font)
        self.temperatureOpenAI = QSlider(self.groupBox_4)
        self.temperatureOpenAI.setObjectName(u"temperatureOpenAI")
        self.temperatureOpenAI.setGeometry(QRect(200, 130, 181, 16))
        self.temperatureOpenAI.setFont(font)
        self.temperatureOpenAI.setMaximum(100)
        self.temperatureOpenAI.setSingleStep(1)
        self.temperatureOpenAI.setValue(70)
        self.temperatureOpenAI.setOrientation(Qt.Orientation.Horizontal)
        self.LLMChocie = QComboBox(self.groupBox_3)
        self.LLMChocie.setObjectName(u"LLMChocie")
        self.LLMChocie.setGeometry(QRect(110, 50, 211, 24))
        self.LLMChocie.setFont(font)
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 50, 51, 21))
        self.label_7.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(490, 10, 111, 20))
        self.label_2.setFont(font)
        self.themeComboBox = QComboBox(self.centralwidget)
        self.themeComboBox.setObjectName(u"themeComboBox")
        self.themeComboBox.setGeometry(QRect(650, 10, 131, 31))
        self.themeComboBox.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 831, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.themeComboBox, self.LLMChocie)
        QWidget.setTabOrder(self.LLMChocie, self.openaiAPIKey)
        QWidget.setTabOrder(self.openaiAPIKey, self.llmMBOX)
        QWidget.setTabOrder(self.llmMBOX, self.temperatureOpenAI)
        QWidget.setTabOrder(self.temperatureOpenAI, self.maxTokenOpenAI)
        QWidget.setTabOrder(self.maxTokenOpenAI, self.systemPromptEdit)
        QWidget.setTabOrder(self.systemPromptEdit, self.testConnectionOpenAI)
        QWidget.setTabOrder(self.testConnectionOpenAI, self.resetDefaultsOpenAI)
        QWidget.setTabOrder(self.resetDefaultsOpenAI, self.chatModeOpenAI)
        QWidget.setTabOrder(self.chatModeOpenAI, self.userInputOpenAI)
        QWidget.setTabOrder(self.userInputOpenAI, self.sendUserInputOpenAI)
        QWidget.setTabOrder(self.sendUserInputOpenAI, self.contextBrowserOpenAI)
        QWidget.setTabOrder(self.contextBrowserOpenAI, self.resetContextOpenAI)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Large Language Model", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"OpenAI Options", None))
        self.testConnectionOpenAI.setText("")
        self.resetDefaultsOpenAI.setText("")
        self.groupBoxChat.setTitle("")
        self.sendUserInputOpenAI.setText("")
        self.resetContextOpenAI.setText("")
        self.label_context.setText(QCoreApplication.translate("MainWindow", u"Context", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"User Input", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"System Prompt", None))
        self.chatModeOpenAI.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Activate Chat Mode", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"API Key", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Max-tokens", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Temperature", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"LLM", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"GUI theme", None))
    # retranslateUi

